// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYS7SKt2rghC-VvKDAsqdPQOqWFBXUv3U',
    appId: '1:927785180950:web:f6b60e4494fe567fd6ba37',
    messagingSenderId: '927785180950',
    projectId: 'final-project-flashcard',
    authDomain: 'final-project-flashcard.firebaseapp.com',
    storageBucket: 'final-project-flashcard.firebasestorage.app',
    measurementId: 'G-CJE6TT58J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdAw1xBrllwezotcEoAtnwMGVsv9eC9E',
    appId: '1:927785180950:android:6e72fe6d4a29e1e3d6ba37',
    messagingSenderId: '927785180950',
    projectId: 'final-project-flashcard',
    storageBucket: 'final-project-flashcard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-rlgd4f-hSvCOroiHPYKM4iPuCBn2mtU',
    appId: '1:927785180950:ios:34e6fca33289d934d6ba37',
    messagingSenderId: '927785180950',
    projectId: 'final-project-flashcard',
    storageBucket: 'final-project-flashcard.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-rlgd4f-hSvCOroiHPYKM4iPuCBn2mtU',
    appId: '1:927785180950:ios:34e6fca33289d934d6ba37',
    messagingSenderId: '927785180950',
    projectId: 'final-project-flashcard',
    storageBucket: 'final-project-flashcard.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYS7SKt2rghC-VvKDAsqdPQOqWFBXUv3U',
    appId: '1:927785180950:web:19fabb094add29d8d6ba37',
    messagingSenderId: '927785180950',
    projectId: 'final-project-flashcard',
    authDomain: 'final-project-flashcard.firebaseapp.com',
    storageBucket: 'final-project-flashcard.firebasestorage.app',
    measurementId: 'G-WJVHHGESWF',
  );
}
